#!/system/bin/sh

echo "Tiempo 230 segundos para Boston"
sleep 230:
echo 3 > /sys/class/leds/green/blink;
echo 3 > /sys/class/leds/green/brightness;
rwsystem
busybox sh /system/bin/fix_permissions;
echo "Reorganizando"
rwsystem;
busybox rm /system/etc/super2/02permisos;
rosystem;
echo 0 > /sys/class/leds/green/blink;
echo 0 > /sys/class/leds/green/brightness;
exit;

