#!/system/bin/sh
#Script Post Instalacion por Super@tmel
# Script 122

echo "Tiempo 140 segundos para Legend"
echo 3 > /sys/class/leds/green/brightness;
echo 3 > /sys/class/leds/green/blink;
sleep 140:
rwsystem
#busybox sh /system/bin/fix_permissions;
echo "Reorganizando"
rwsystem;
busybox rm /system/etc/super2/02permisos;
rosystem;
echo 0 > /sys/class/leds/green/blink;
echo 0 > /sys/class/leds/green/brightness;
exit;
