#!/system/bin/sh
#Script Post Instalacion por Super@tmel
# Script 123

echo "Instalando Lenguaje para GPS si es necesario en 100 segundos"
sleep 100;
echo " Activando Instalador GPS"
if [ -e /data/lang/com.svox.langpack.installer.apk ];
	then
echo "***** Se instalara GPS";
busybox chown system.system /data/installlangpack;
busybox chmod 0755 /data/installlangpack;
	/data/installlangpack &
fi;
exit;
